### ISSUE TITLE
Any leaderboard?

### ISSUE THREAD

**Issue by zhimin-z** [salesforce/factualNLG#1]

**Comment by tingofurro** [comment]
Hey Zhimin,

Thanks, you raise a good point. We currently haven't created a dynamic benchmark that people can contribute to, but we could do so. Are there certain models you'd like to see how they perform on SummEdits, I'd be happy to run them if they're on the HF hub.

Philippe

**Comment by zhimin-z** [comment]
Found it and closed for now
